"""
topics.py

Creates a list of topics for the book.

If book/topics.txt exists, only create the index.tex file. This allows
for manual revision of topics after they are generated by chat-gpt.

"""

from openai import OpenAI

client = OpenAI()

import json

with open("src/layout.json", "r+") as f:
    layout = json.load(f)

print("Building layout...")
with open("book/chapters.tex", "w+") as f:
    output = []
    idx = 0

    for chapter in layout:
        output.append(r"\chapter{%s}" % chapter)
        for poem in layout[chapter]:
            idx += 1
            output.append(f"\input{{book/poems/{idx:03d}_{poem}}}")

    f.write("\n".join(output))
