"""
topics.py

Creates a list of topics for the book.

If book/topics.txt exists, only create the index.tex file. This allows
for manual revision of topics after they are generated by chat-gpt.

"""

import os

from openai import OpenAI

client = OpenAI()

topics_txt_path = os.environ["TOPICS_TXT_PATH"]
chapters_index_path = os.environ["CHAPTERS_INDEX_PATH"]

try:
    with open(topics_txt_path, "r+") as f:
        topics = [line.strip() for line in f.readlines()]
except FileNotFoundError:
    print("Generating list of topics...")
    chat_completion = client.chat.completions.create(
        messages=[
            {
                "role": "user",
                "content": "Top 100 poetry themes by frequency. List only. Comma separated.",
            }
        ],
        model="gpt-4-turbo-preview",
    )

    topics = chat_completion.choices[0].message.content.split(",")
    with open(topics_txt_path, "w+") as f:
        f.write("\n".join(topics))

print("Writing index...")
with open(chapters_index_path, "w+") as f:
    index = [
        f"\input{{book/chapters/{idx:03d}_{topic}}}" for idx, topic in enumerate(topics, 1)
    ]
    f.write("\n".join(index))
